### ISSUE TITLE
Incompatible with "Shmovment"

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/cool-thirdperson-view#1]
Workshop addon "https://steamcommunity.com/sharedfiles/filedetails/?id=2737702541&searchtext=shmovement" renders playermodel invisible in cl_nte_enabled 1 and draws only viewmodel in the position of the player's eyes. Standard Garry's Mod "thirdperson" works as expected.
Tested with only CTV, CalcView Priority System, and Shmovment installed.

P.S. Very sleek smoothing, however crouch transition could use some kind of lerp or something

**Comment by relaxtakenotes** [comment]
shmovement overrides calcview which breaks things. cant fix that unless i forcefully disable that hook but then the whole point of that mod is lost. very sad...
to make crouching smoother you can set your actual crouching speed to be slower. use my better movement mod, player speed changer or something else to do that.

**Comment by relaxtakenotes** [comment]
oh also go check https://github.com/relaxtakenotes/gm-action-music/issues/2, i might have fixed that dumb issue

**Comment by Lombaxtard** [comment]
> shmovement overrides calcview which breaks things. cant fix that unless i forcefully disable that hook but then the whole point of that mod is lost. very sad... to make crouching smoother you can set your actual crouching speed to be slower. use my better movement mod, player speed changer or something else to do that.

Sure, that makes it smoother, but the view still jumps down when crouching only to snap back a bit higher, no matter how smooth it might be with slower player_speed_ducking/unducking. I think ViewExtension got it better, but I'll have to verify that later...

**Comment by Lombaxtard** [comment]
> oh also go check [relaxtakenotes/gm-action-music#2](https://github.com/relaxtakenotes/gm-action-music/issues/2), i might have fixed that dumb issue

I got your email, will do when I'll have some more free time

**Comment by relaxtakenotes** [comment]
that crouch thing will be fixed in the next update. i figured out what u actually meant
