### ISSUE TITLE
Issue: Causes random movement when player is forced to crouch

### ISSUE THREAD

**Issue by dweetacular** [relaxtakenotes/cool-thirdperson-view#11]
When the player is in a small space where they can't stand up / are forced to be crouching, they continuously walk in a certain direction. The direction is apparently related to the height of the space, i.e. a very small crouch space moves towards negative on the X axis, a slightly larger one moves positive on the X axis. It also seems to interrupt movement inputs during this, but it might just be due to the speed.

Using Chromium / 64-bit branch, occurs regardless of whether the addon is enabled in the spawn menu.

**Comment by relaxtakenotes** [comment]
oh yeah that's my epic feature that's meant to prevent your head from clipping. i couldn't get it working well at all so i'll probably remove it soon
