### ISSUE TITLE
Suggestion: Add command or a bind for a manual side switcher

### ISSUE THREAD

**Issue by fakefurryFactory** [relaxtakenotes/cool-thirdperson-view#13]
I love this addon, but I feel like the auto side switch is a little janky, and I prefer manually switching shoulders.

**Comment by relaxtakenotes** [comment]
cl_nte_autoside_enabled 0
cl_nte_default_side -1, 0, 1 
https://developer.valvesoftware.com/wiki/Incrementvar on cl_nte_default_side
