### ISSUE TITLE
A question about the compatibility of the standard sight of the game with the sight from the mod

### ISSUE THREAD

**Issue by paczarma** [relaxtakenotes/cool-thirdperson-view#22]
For some reason, the standard sight from the game is displayed along with the sight that comes with the mod... Is this how it should be?

If not, could you recreate a feature that would allow to automatically turn on or off the standard sight when you turn on or off the mod using options?

![2024-07-14_23-03-01](https://github.com/user-attachments/assets/b18f749c-516b-42d0-8544-0489baac9c73)

**Comment by relaxtakenotes** [comment]
use crosshair 0
