### ISSUE TITLE
Crouch height issue and 1st person view bugs

### ISSUE THREAD

**Issue by Spr-Aachen** [relaxtakenotes/cool-thirdperson-view#3]
Hi dear author. I really like this mod, but I've encountered some problem.
1. After toggling the `hybrid immersive firstperson` option, I got view bugs while trying to use with lean mod like Tactical Leaning or Arc9's lean function. Plus, sometimes the PM's hand model goes far ahead lol:)
2. It seems that CTV has changed PM's crouch height, no mater I selected `thirdperson mode` or `firstperson mod`, I found the PM's crouch height a bit higher than before, this made me hard to get through pipes in game map.
Any ideas?

**Comment by relaxtakenotes** [comment]
1) yeah it's known but idk how to fix them yet
2) i check for the head being inside something so of it is it pushes you back. try to use a prone mod to go through vents/tight spaces

**Comment by Spr-Aachen** [comment]
Thanks for the reply! I think I might have a 'solution'.
1. Perhaps you can add a concommand to support fast toggling the CTV mod so that we can just use the thirdperson view before the firstperson view has been fixed? I know it sounds a little bit disapointing but this is already an excellent thirdperson view mod even without the firstperson view mode.
2.  Nice solution! I don't even know there are any prone mods before, now I can get a better game experience:)
