### ISSUE TITLE
True Aim does not adjust together with View Cam in Immersive Firstperson mode.

### ISSUE THREAD

**Issue by Haano137** [relaxtakenotes/cool-thirdperson-view#6]
VANILLA:
![image](https://github.com/relaxtakenotes/cool-thirdperson-view/assets/71540568/cd12dcdf-9ee1-4336-b628-138de991c1d8)
![image](https://github.com/relaxtakenotes/cool-thirdperson-view/assets/71540568/5db8787a-5649-4c79-bfa5-b4d4bf41cf83)

IMMERSIVE FIRSTPERSON:
![image](https://github.com/relaxtakenotes/cool-thirdperson-view/assets/71540568/4859abe6-218f-4511-8c52-11dd78f4d722)
![image](https://github.com/relaxtakenotes/cool-thirdperson-view/assets/71540568/631e1587-f1e2-4063-a8ab-91edd4daae22)

**Comment by relaxtakenotes** [comment]
use dynamic height adjustment mod
